# Generated by Django 4.1.1 on 2022-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210217_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
