# Generated by Django 4.1.1 on 2022-11-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_homepageslideshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
