# Generated by Django 4.1.1 on 2022-11-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
