# Generated by Django 4.1.1 on 2022-11-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.area'),
        ),
    ]
