# Generated by Django 4.1.1 on 2022-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customeraddress_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_feature',
            field=models.CharField(choices=[('YE', 'Yes'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
