# Generated by Django 4.1.1 on 2022-11-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orderitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
