# Generated by Django 4.1 on 2022-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orderitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_orders',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
