# Generated by Django 4.1.1 on 2022-11-19 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_total_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.area'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.province'),
        ),
    ]
