# Generated by Django 4.1.1 on 2022-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orderdetail_area_orderdetail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='address',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='area',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='city',
            field=models.CharField(default='Not Set', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='province',
            field=models.CharField(default='Not Set', max_length=200),
        ),
    ]
