# Generated by Django 4.1.1 on 2022-11-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_orderdetail_address_alter_orderdetail_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='area',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='province',
            field=models.CharField(default='', max_length=30),
        ),
    ]
