# Generated by Django 4.1.1 on 2022-11-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_orderdetail_area_alter_orderdetail_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='area',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='province',
            field=models.CharField(default='', max_length=30),
        ),
    ]
